# Generated by Django 4.1.2 on 2022-12-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department_code', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('major_type', models.BooleanField(null=True)),
                ('major', models.CharField(default='', max_length=5)),
                ('minor', models.CharField(default='', max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('num_classes', models.IntegerField()),
                ('num_labs', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('credit_au', models.IntegerField()),
                ('review_total_weight', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='LectureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectures', models.ManyToManyField(to='api.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prof_id', models.IntegerField()),
                ('review_total_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('begin', models.IntegerField()),
                ('end', models.IntegerField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_saved', models.BooleanField()),
                ('lecture_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lecturelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cpuser')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professor'),
        ),
        migrations.CreateModel(
            name='Examtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('begin', models.IntegerField()),
                ('end', models.IntegerField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lecture')),
            ],
        ),
        migrations.AddField(
            model_name='cpuser',
            name='lecture_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lecturelist'),
        ),
    ]
